
sudo: required

branches:
  only:
    - estonia

services: docker

install: true

language: C

jobs:
  include:
   - stage: build
     script: scripts/build-base.sh
   - stage: build
     script: scripts/build-builder.sh
